### ISSUE TITLE
Documentation: Minimum Required Django Version

### ISSUE THREAD

**Issue by reduxionist** [pmclanahan/django-celery-email#12]
Project's GitHub description states compatibility with Django 1.2+, but readme indicates 1.3+. There's no way to open a PR for project metadata so I thought I'd open this issue instead.

Thanks for sharing your code!

**Comment by pmclanahan** [comment]
Thanks! Good catch. I merged a PR recently that updated that to 1.3+. Since 1.3 isn't supported by Django any longer I supposed saying 1.4+ is reasonable, but the tests do pass with 1.3. I'll update the description.
