### ISSUE TITLE
email doesn't send successfully

### ISSUE THREAD

**Issue by Mark-Shine** [pmclanahan/django-celery-email#15]
ENV: django 1.6.5, celery 3.1.17, python 2.7

Celery has setup, everything is ok. I have test function add().

I go with instruction, but nothing happened.

So l looked into the code, and change this line

@shared_task(**TASK_CONFIG)
def send_emails(messages, backend_kwargs=None, **kwargs):

to 

@shared_task
def send_emails(messages, backend_kwargs=None, **kwargs):

then it works!

**Comment by jayfk** [comment]
I had to add `CELERY_IMPORTS = ["djcelery_email.tasks"]` to settings.py to get it working.

**Comment by pmclanahan** [comment]
@Mark-Shine have you tried the above suggestion? Does that fix it as well? We need to keep the `TASK_CONFIG` bit so that tasks can be configured in settings.
