### ISSUE TITLE
HTML only emails sent as plain text

### ISSUE THREAD

**Issue by gnarvaja** [pmclanahan/django-celery-email#18]
Messages with content_subtype overridden to "html" are sent as plain text when passing through djcelery.

It's because in the serialization process (email_to_dict function), only some attributes are copied. 

Fix in https://github.com/pmclanahan/django-celery-email/pull/17

**Comment by samcheng** [comment]
I can confirm the bug, and the fix looks pretty good to me!  Is there any timeline for a 1.1.2 release, so I don't have to fork?  Thanks for the useful library!

**Comment by pmclanahan** [comment]
@samcheng I can cut a release today. I'll post here when I do.

**Comment by pmclanahan** [comment]
It's up. Thanks again @gnarvaja !

https://pypi.python.org/pypi/django-celery-email/1.1.2

**Comment by samcheng** [comment]
Excellent!  Thank you, Paul!
