### ISSUE TITLE
Is the python 3 supporting?

### ISSUE THREAD

**Issue by pahaz** [pmclanahan/django-celery-email#32]

**Comment by kevin-brown** [comment]
[It should.](https://github.com/pmclanahan/django-celery-email/blob/eef37ecc727bfc8e2cc5e069b26d44eab44f2f81/setup.py#L44-L47)

**Comment by auvipy** [comment]
any plan to celery 3.x?

**Comment by pmclanahan** [comment]
It is tested and working with both Python 3.3+ and Celery 3.0 and 3.1. You can find all of the combinations of Python, Django, and Celery that are currently tested in the `tox.ini` file in the repo. If there are specific issues with a particular combination please open an issue.

**Comment by pahaz** [comment]
Can you change pypi docs and write about python3 support ?
