### ISSUE TITLE
Does it work with JSON serialisation?

### ISSUE THREAD

**Issue by barseghyanartur** [pmclanahan/django-celery-email#42]
I'm upgrading an old project that did make use of `django-celery-email` version 1.0.4.

Can `django-celery-email` (latest version of) handle JSON serialisation? It hasn't been available in 1.0.4.

Thanks in advance!

**Comment by pmac** [comment]
Yes. The latest version does support JSON.

**Comment by barseghyanartur** [comment]
@pmac:

Thanks for the quick reply!
