### ISSUE TITLE
Celery 4.x support

### ISSUE THREAD

**Issue by barseghyanartur** [pmclanahan/django-celery-email#43]
Are there plans for supporting Celery 4.x in nearest future? If so, could you give an estimation?

**Comment by pmac** [comment]
I don't really have plans on working on this. I've not used it personally in years. I'm happy to review and merge pull requests however, so if you or someone else gets the time please let me know.

FYI: pmac is my main  account now, pmclanahan is an  alternate  I use for some orgs

**Comment by barseghyanartur** [comment]
@pmac:

Thanks for the quick reply.

**Comment by georgmzimmer** [comment]
I may be needing it on a celery 4 project soon, if so, i'll take a look at it.  Any idea what isn't working?

**Comment by barseghyanartur** [comment]
@georgmzimmer:

Are you upgrading from old Django/Celery stack?

**Comment by georgmzimmer** [comment]
No, new project.

**Comment by barseghyanartur** [comment]
@georgmzimmer:

Ok. No idea what didn't work. I was trying to replace an old stack (Celery 3.x, django-celery, django-celery-transactions, django-celery-emails, kombu) with upgraded versions (upgrade Celery to 4.x, wipe out django-celery, replace django-celery with new apps). It seemed to work until a point, when I had to touch a way too many things that didn't work (risk going over the budget). So I just stopped.

I'll stay subscribed to this issue and hopefully over a year or so I can try again. :)

**Comment by poxip** [comment]
I'm working on upgrading it to the latest Celery, will send a PR when I finish.

**Comment by poxip** [comment]
PR https://github.com/pmclanahan/django-celery-email/pull/44

**Comment by barbossa** [comment]
@pmac can you merge PR #44 to master? I realy need this!
Thanks!

@poxip thanks for adding support for Celery 4.x!

**Comment by pmclanahan** [comment]
I can. Might not get to it until Monday though. That soon enough?
-- 
-- pmac

**Comment by barbossa** [comment]
Monday will be okay.
@pmclanahan thanks for quick reply.

**Comment by pmac** [comment]
#44 is now merged and v 2.0.0 is now released on PyPI. Thank you very much @poxip 🎉
