### ISSUE TITLE
Django 2.0 compatibility?

### ISSUE THREAD

**Issue by SebJansen** [pmclanahan/django-celery-email#48]
Does it work wit Django 2.0?

**Comment by pmac** [comment]
Not sure yet. We can use this issue to test and fix things if not. Thanks for filing.

**Comment by hendrikschneider** [comment]
I updated the tox configuration and it works.

#49

**Comment by amureki** [comment]
That is great @hendrikschneider 
Can we, please, update the package? @pmac 

Thank you!

**Comment by pmac** [comment]
Sure! Thanks all. I’ll look into this later today.

**Comment by ACPK** [comment]
@pmac - Any updates on merging the PR?

**Comment by pmac** [comment]
Hi @ACPK. The PR merged and didn't make any changes to the package itself, only the tests. So I don't think there is anything to change. Please correct me if I'm wrong, but I think this one is complete and I just failed to close it.
