### ISSUE TITLE
Django 2.1 support

### ISSUE THREAD

**Issue by barseghyanartur** [pmclanahan/django-celery-email#55]
Is Django 2.1 officially supported? If so, please, update tox, travis and supported Django versions clause. In my tests (clone, install reqs, run tests ``./runtests.py``) it seems to work.

**Comment by jmsmkn** [comment]
I think this issue can be closed as #58 has been merged, no changes to the module were needed for Django 2.1 and 2.2 support.

**Comment by pmac** [comment]
Agreed. Thanks again!
