### ISSUE TITLE
Import under Django 3.0 fails

### ISSUE THREAD

**Issue by peterthomassen** [pmclanahan/django-celery-email#67]
The [Python 2 compatibility APIs are removed with the Django 3.0 release](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis). Importing from `djcelery_email.utils` thus leads to `ImportError: cannot import name 'six' from 'django.utils'`.

**Comment by philippbosch** [comment]
#66 already addresses this and was merged into master just now.

**Comment by peterthomassen** [comment]
thanks!

**Comment by JaredOzzy** [comment]
I've upgraded my django, celery and dj-celery to the latest versions and im getting the issue

>  ImportError: cannot import name 'six'

`File "/usr/local/lib/python3.6/site-packages/djcelery_email/backends.py", line 4, in <module>
django_1         |     from djcelery_email.tasks import send_emails
django_1         |   File "/usr/local/lib/python3.6/site-packages/djcelery_email/tasks.py", line 7, in <module>
django_1         |     import djcelery_email.conf  # noqa
django_1         |   File "/usr/local/lib/python3.6/site-packages/djcelery_email/conf.py", line 1, in <module>
django_1         |     from appconf import AppConf
django_1         |   File "/usr/local/lib/python3.6/site-packages/appconf/__init__.py", line 2, in <module>
django_1         |     from .base import AppConf  # noqa
django_1         |   File "/usr/local/lib/python3.6/site-packages/appconf/base.py", line 4, in <module>
django_1         |     from django.utils import six
django_1         | ImportError: cannot import name 'six'`

**Comment by philippbosch** [comment]
> File "/usr/local/lib/python3.6/site-packages/appconf/base.py", line 4, in
> from django.utils import six

@JaredOzzy this is due to an import in django-appconf, not django-celery-email

**Comment by JaredOzzy** [comment]
Ah you are correct, Thank you sir!
